/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as Index2RouteImport } from './routes/index 2'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ListsRouteImport } from './routes/lists'
import { Route as MealsRouteImport } from './routes/meals'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as StaplesRouteImport } from './routes/staples'
import { Route as ShoppingIndexRouteImport } from './routes/shopping.index'
import { Route as ShoppingMercadonaRouteImport } from './routes/shopping.mercadona'
import { Route as ShoppingReviewRouteImport } from './routes/shopping.review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const Index2Route = Index2RouteImport.update({
  id: '/index 2',
  path: '/index 2',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsRoute = MealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const StaplesRoute = StaplesRouteImport.update({
  id: '/staples',
  path: '/staples',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingIndexRoute = ShoppingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShoppingRoute,
} as any)
const ShoppingMercadonaRoute = ShoppingMercadonaRouteImport.update({
  id: '/mercadona',
  path: '/mercadona',
  getParentRoute: () => ShoppingRoute,
} as any)
const ShoppingReviewRoute = ShoppingReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ShoppingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/history': typeof HistoryRoute
  '/index 2': typeof Index2Route
  '/join': typeof JoinRoute
  '/lists': typeof ListsRoute
  '/meals': typeof MealsRoute
  '/preferences': typeof PreferencesRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRouteWithChildren
  '/staples': typeof StaplesRoute
  '/shopping/mercadona': typeof ShoppingMercadonaRoute
  '/shopping/review': typeof ShoppingReviewRoute
  '/shopping/': typeof ShoppingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/history': typeof HistoryRoute
  '/index 2': typeof Index2Route
  '/join': typeof JoinRoute
  '/lists': typeof ListsRoute
  '/meals': typeof MealsRoute
  '/preferences': typeof PreferencesRoute
  '/settings': typeof SettingsRoute
  '/staples': typeof StaplesRoute
  '/shopping/mercadona': typeof ShoppingMercadonaRoute
  '/shopping/review': typeof ShoppingReviewRoute
  '/shopping': typeof ShoppingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/history': typeof HistoryRoute
  '/index 2': typeof Index2Route
  '/join': typeof JoinRoute
  '/lists': typeof ListsRoute
  '/meals': typeof MealsRoute
  '/preferences': typeof PreferencesRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRouteWithChildren
  '/staples': typeof StaplesRoute
  '/shopping/mercadona': typeof ShoppingMercadonaRoute
  '/shopping/review': typeof ShoppingReviewRoute
  '/shopping/': typeof ShoppingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/history'
    | '/index 2'
    | '/join'
    | '/lists'
    | '/meals'
    | '/preferences'
    | '/settings'
    | '/shopping'
    | '/staples'
    | '/shopping/mercadona'
    | '/shopping/review'
    | '/shopping/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/history'
    | '/index 2'
    | '/join'
    | '/lists'
    | '/meals'
    | '/preferences'
    | '/settings'
    | '/staples'
    | '/shopping/mercadona'
    | '/shopping/review'
    | '/shopping'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/history'
    | '/index 2'
    | '/join'
    | '/lists'
    | '/meals'
    | '/preferences'
    | '/settings'
    | '/shopping'
    | '/staples'
    | '/shopping/mercadona'
    | '/shopping/review'
    | '/shopping/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  HistoryRoute: typeof HistoryRoute
  Index2Route: typeof Index2Route
  JoinRoute: typeof JoinRoute
  ListsRoute: typeof ListsRoute
  MealsRoute: typeof MealsRoute
  PreferencesRoute: typeof PreferencesRoute
  SettingsRoute: typeof SettingsRoute
  ShoppingRoute: typeof ShoppingRouteWithChildren
  StaplesRoute: typeof StaplesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index 2': {
      id: '/index 2'
      path: '/index 2'
      fullPath: '/index 2'
      preLoaderRoute: typeof Index2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists': {
      id: '/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof ListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals': {
      id: '/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof MealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staples': {
      id: '/staples'
      path: '/staples'
      fullPath: '/staples'
      preLoaderRoute: typeof StaplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping/': {
      id: '/shopping/'
      path: '/'
      fullPath: '/shopping/'
      preLoaderRoute: typeof ShoppingIndexRouteImport
      parentRoute: typeof ShoppingRoute
    }
    '/shopping/mercadona': {
      id: '/shopping/mercadona'
      path: '/mercadona'
      fullPath: '/shopping/mercadona'
      preLoaderRoute: typeof ShoppingMercadonaRouteImport
      parentRoute: typeof ShoppingRoute
    }
    '/shopping/review': {
      id: '/shopping/review'
      path: '/review'
      fullPath: '/shopping/review'
      preLoaderRoute: typeof ShoppingReviewRouteImport
      parentRoute: typeof ShoppingRoute
    }
  }
}

interface ShoppingRouteChildren {
  ShoppingMercadonaRoute: typeof ShoppingMercadonaRoute
  ShoppingReviewRoute: typeof ShoppingReviewRoute
  ShoppingIndexRoute: typeof ShoppingIndexRoute
}

const ShoppingRouteChildren: ShoppingRouteChildren = {
  ShoppingMercadonaRoute: ShoppingMercadonaRoute,
  ShoppingReviewRoute: ShoppingReviewRoute,
  ShoppingIndexRoute: ShoppingIndexRoute,
}

const ShoppingRouteWithChildren = ShoppingRoute._addFileChildren(
  ShoppingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  HistoryRoute: HistoryRoute,
  Index2Route: Index2Route,
  JoinRoute: JoinRoute,
  ListsRoute: ListsRoute,
  MealsRoute: MealsRoute,
  PreferencesRoute: PreferencesRoute,
  SettingsRoute: SettingsRoute,
  ShoppingRoute: ShoppingRouteWithChildren,
  StaplesRoute: StaplesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
